### ISSUE TITLE
Systematic avoidance of big overlaps

### ISSUE THREAD

**Issue by bhagavadgitadu22** [deprekate/genotate#3]
I am trying to find the best way to identify overlapping genes in my complete viruses extracted from metagenomes. I tried genotate hoping that it would identify them contrary to prodigal-gv and phanotate (which forbids big overlaps in their algorithms).

I compared genotate to prodigal-gv and a homemade method consisting in:
-	Blasting all EMBOSS ORFs between a start and a stop codon bigger than 60bp
-	Considering hits as “true” genes

I plotted the results for all viruses with pycirclize with from center to the outside:
-	The EMBOSS genes obtained mapped on the 3 possible frames (light grey)
-	The genotate genes obtained mapped on the 3 possible frames (darker grey)
-	The prodigal-gv genes obtained

Here is a few examples of the problem I have with genotate which seems to systematically “avoid” big overlaps. For the first figure for instance:
-	A big overlap between a green and pink gene is observed in EMBOSS
-	None of those genes is found by genotate
-	The pink one only is identified by prodigal-gv
What do you think of this issue? Is there a way to use genotate to find more overlaps? Or can I rely on my “homemade” EMBOSS method?
![image](https://github.com/user-attachments/assets/fc61ee09-0c7c-4682-8e09-59b87681a472)
![image](https://github.com/user-attachments/assets/61a82e39-d636-47e8-8180-9b5bf68a8417)
![image](https://github.com/user-attachments/assets/4e77907a-7e9f-4567-afb9-9ffb6e2ae15e)
![image](https://github.com/user-attachments/assets/dfafdba6-cb70-486d-a785-f277470143fb)

**Comment by deprekate** [comment]
Do you know if the viral genomes are phages or Eukaryotic viruses.  The current Genotate coding models were trained on only phages (in hindsight, I should have left the Euk viruses in the training data), so Genotate under-performs on Euk viruses. 

Are you able to share the genomes?  I would be interested in manually inspecting what could be going wrong.  One thing I see (at least with the first example) is that while Genotate does allow overlapping genes (and even completely overlapping 'nested' genes), it does limit them to the same strand.  It looks like the green/pink genes in the first example are on opposite strands, with the ends of each overlapping.  During the first iteration of Genotate, it determines which strand is the coding strand at every point on the genome, so presumably it would choose either the region that the entire green gene is on or the entire region that the pink gene is on, which would end up truncating one of the genes.  I do pad/extend the ends of both initial strand regions to allow for some opposite strand overlaps, but probably not enough to capture which ever gene is on the strand that gets truncated.

I am surprised to see even large non overlapping genes missing from the Genotate gene calls.  If the genomes are phage, and since they are MAGs, there might not have been any related taxa present in the Genotate training genomes, which might explain the missing genes.  

Depending on what database you use for your blasting, and how well you curate the hits, your manual method may be quite accurate. Despite my best efforts with Phanotate and now Genotate, I still cannot achieve the level of accuracy that manual genome annotation provides : )

**Comment by bhagavadgitadu22** [comment]
The genomes are phages (mainly Caudovirales) but indeed they might be quite far from existing databases of viruses. I obtained from metagenomes using VIBRANT followed by COBRA and vRhyme and I kept only high-quality viruses according to CheckV. I send them to your email address with the annotated figures I produced with pycirclize (at deprekate@gmail.com).

I used the pharokka took to annotate all my gene calls including the EMBOSS ORFs: it runs MMseqs2 on PHROGs, CARD, VFDB and PyHMMER on PHROGs (threshold e=1E-05). I assumed because these databases are well curated and the threshold was low I did not need additional manual curation. How would you proceed to further manually inspect the annotations?

I missed the fact that genotate excludes opposite strands overlaps. I do see them regularly occuring in my dataset though. Would it be an extra complication to allow genotate to look for opposite strands overlaps? I guess that would mean to multiply the computational burden by 2.

**Comment by deprekate** [comment]
ah, it looks like those long overlaps are actually long stretches of NNNs where contigs have been joined, and so cause long spurious open reading frames.  

Here is that region that contains the green/pink overlapping genes in your first example.   I can see there is a fragment of a gene that is missing from the Genotate gene calls just to the left of the yellow box in the +3 frame which would be the pink gene from your T2_S3_B_v_bin_16 circle plot, as well as another missing gene fragment to the right of the yellow box in the bottom most -3 frame that would correspond to the green gene from your circle plot.
![Screenshot 2024-08-01 at 3 09 37 PM](https://github.com/user-attachments/assets/e3fee6b6-e053-4511-b2ff-79efc10766d2)
Any ORF based gene finder will allow genes to be called that stride a gap, but it shouldn't be allowed since the relative frames of the flanking regions are not known and/or whether the regions are even contiguous. 

I suspect many of your overlaps are these gap-joined regions that mimic long open reading frames; and since they contain a fragment of a gene, they do return local homology hits from tools like blast. 

___
The presence of the gap, rather than the contig ending, causes Genotate to rule out the gene fragment due to some internal logic. I suppose I should have Genotate scan an input sequence and split the genome on long stretches of NNNs. If I pull out just that piece of T2_S3_B_v_bin16 and then run it through Genotate, it correctly predicts the missing fragment:
![Screenshot 2024-08-01 at 3 09 50 PM](https://github.com/user-attachments/assets/b9dd8106-d0fb-40f9-a67d-f0da49ad69fd)

*oh the grey box mRNA features in my figures are the strand predictions during the first pass of Genotate, which I mentioned are extended/padded a little beyond the original predictions.  You can see how it does allow for overlapping opposite strand genes just a little bit

**Comment by bhagavadgitadu22** [comment]
Thank you very much. Indeed these erroneous genes should definitely not be called because of the 2 reasons you mentioned (plus the fact that you do not know if start/stop codons happened in the NNN stretch). Considering binning is so common in metagenomics that would imply many genes predicted in those studies are actually artefacts this is a bit concerning.
